### ISSUE TITLE
[FEATURE] Configuration should not be part of repository

### ISSUE THREAD

**Issue by thoechsmann** [thepeanutgalleryandco/create-and-mint-nft-collection#35]
The configuration should not be part of the repository. 

Rename everything of the template/demo configuration. Those renamed files are part of the repo.

src/config.js -> src/config_demo.js (actually it would be even better to not have that in the src folder at all)
layers -> layer_demo

This would make it easier to contribute to the project without stashing stuff all the time. It is also a cleaner way.

**Comment by thepeanutgalleryandco** [comment]
@thoechsmann can you be more specific as to what exactly is an issue with the current src/config.js files? At the moment, most users are non technical in terms of coding and it is even difficult for them to update a config file that contains the demo items inside of it.....I can only imagine how "difficult" it will be for them to manually update everything or create their own layer files. It will be a training nightmare.

**Comment by thoechsmann** [comment]
Beside non-practical for devs the current configuration is confusing as it is in different places of the project. Some changes even must be made in the constants folder. It would be better to have the config folder with all config data as a parameter when building from the command line. In the end  is is a command line tool that can expect rough knowledge on how this works.

**Comment by thepeanutgalleryandco** [comment]
Not sure if you have seen or worked on the base repos yet, but I am building as a 3rd or 4th dev on the repo, which means its got bits and pieces from everyone's configurations sitting at different places. Since I don't have videos out and big explanations (other than the README), I feel keeping it as is for the time being is fine. 99% of the users thus far has been able to configure the 3 files without issues and from there, their generations work.

I agree that configuration shouldn't be scattered like it currently is, but I would rather split that out in a huge version update where we then move all config items into a single, proper JSON configuration file, where we can then also add a demo configuration file as reference. Then everything will be merged and properly maintained, but will need a lot of video training and re-writes. 

For now, I will leave this here as a reminder for when the overhaul is done.

**Comment by thoechsmann** [comment]
Yeah. You are absolutely right that this change is not required to use the tool. And also that it would move the codebase away from the base repo. However this will happen and did happen anyway. One solution would be to just contribute the the base repo and not have this version which is not a real fork. Not sure if github allows for subrepos that could be a solution to have still a tool with is incorporating various tools into one.

**Comment by thepeanutgalleryandco** [comment]
Can we close this feature request and handle this when the code base overhaul is done?
