### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by razielll** [thepeanutgalleryandco/create-and-mint-nft-collection#6]
https://github.com/thepeanutgalleryandco/create-and-mint-nft-collection/blob/f7e84ce2bd929d0e2b1f483fb61a7d5e54490951/src/main.js#L179

wont it be better to check  if (!selectedElement.name.trim().includes('blank') 

this will allow disregarding any asset with 'blank' in its string, allowing maximal flexibility, as long as blank isn't used as a prop name

**Comment by thepeanutgalleryandco** [comment]
Thank you @razielll for this request. I have given it thought and I think creators might have two use cases.

1. A creator would like to remove Blank.png files as it is simply a blank to increase your layer counts and to allow some versatility to how your NFTs look.
2. A creator would like to remove all notions of *Blank*.png files as they added multiple blank filenames for versatility.

I have decided to make the following change in the upcoming release, keen to hear your thoughts.

**I have added a new setting in the constants/nft_details.js file:**
ignoreAllNamesWithBlank: true // This value is a boolean with a value of false or true. If true, then any layer item that contains the word blank within the filename will be skipped from being added to the metadata information. When set to false, then the information will be added to the metadata. E.x white_eyes_blank #100.png will be added to metadata if set to false, while being skipped if true.

**I have modified the src/main.js file:**
const addAttributes = (_element) => {
  let selectedElement = _element.layer.selectedElement;

  //Added ability for user to state whether they are using blank images or blank keyword within image names so that the code can already cater for it as the norm is to remove blanks from attribute lists.
  if (NFT_DETAILS.ignoreAllNamesWithBlank) {
    if (!selectedElement.name.trim().toLowerCase().includes("blank")) {
      addToAttrbutesList(_element.layer.name, selectedElement.name);
    }
  } else if (NFT_DETAILS.blankFilenameInLayers) {
    if (selectedElement.name.trim().toLowerCase() !== "blank") {
      addToAttrbutesList(_element.layer.name, selectedElement.name);
    }
  } else {
    addToAttrbutesList(_element.layer.name, selectedElement.name);
  }
};


These changes will allow the user to completely remove anything with the word blank in the name of the layer OR to simply remove the single blank item, but keep other blank names in their metadata.

Please let me know if this will resolve your issue?

**Comment by razielll** [comment]
ignoreAllNamesWithBlank - blankFilenameInLayers - those are 2 vars saying the same thing right ? lets consolidate them to
'displayBlankFiles' - true/false -> true -> doesn't check a thing, false -> checks the .includes('blank') code ? 


I'm not sure what the second check helps to determine that the first one will fail at ?
```
} else if (NFT_DETAILS.blankFilenameInLayers) {
if (selectedElement.name.trim().toLowerCase() !== "blank") {
addToAttrbutesList(_element.layer.name, selectedElement.name);
}
```

**Comment by thepeanutgalleryandco** [comment]
@razielll apologies, I didn't see your comment before I merged and it closed the ticket automatically on merge.

So the reason I kept the second check is for the following reason.
If I have the following folder structure with layer items:
Background
- black #10.png
- blue #10.png
- blank #100.png
- blank_with_orange #1.png

The two settings and different checks give me the following.

If ignoreAllNamesWithBlank = true, then remove both "blank_with_orange #1.png" and "blank #100.png" from the properties.

If ignoreAllNamesWithBlank = false and blankFilenameInLayers = true, then remove only the "blank #100.png" file from the properties and keep the "blank_with_orange #1.png" in the properties.

If ignoreAllNamesWithBlank = false and blankFilenameInLayers = false, then keep both "blank_with_orange #1.png" and "blank #100.png" in the properties.

Hope this makes sense. I have merged it like this into v1.3.0.

**Comment by razielll** [comment]
Actually I think it doesn't make sense ? based on the variable names the behaviour might be counter-intuitive
let me try to explain
first condition makes perfect sense. if i chose to ignoreAllNamesWithBlank - don't include any. 

second case: 
ignoreAllNamesWithBlank - false. Ok, so we consider the blanks, we DON't ignore them.
blankFileNameInLayers - this indicates (by the name) I want 'blank' file names to be counted, so why would blank #100 be removed ? but blank with orange #1 got in ?
ok - I see that it DOES make sense, but very very EXPLICITLY. maybe a better name could be `blankFilenameInLayers ` -> `ignoreExactBlankName` - better respresents the behaviour ?

Cheers

**Comment by thepeanutgalleryandco** [comment]
Thanks for the suggestion, I am happy to move to this naming convention and it is more explicit. It will be in the new 1.3.1 minor update.
