### ISSUE TITLE
layerItemsMaxRepeatedTraits still returns duplicates

### ISSUE THREAD

**Issue by marcneagu** [thepeanutgalleryandco/create-and-mint-nft-collection#64]
Hello, and thank you for sharing your work with us!

I have 7600 different layers in the folder(s) "Body x", and there will be a total of 7600 NFTs. I want every single layer to appear in the collection, and I want NO duplicates of the layers in the "Body" folders.
So I managed to type 7600 lines of code with "layerItemsMaxRepeatedTraits" and I still have a few items that do NOT appear (ex: Areion 275) and some layers appear multiple times (ex: Areion 292). Am I getting wrong this function, or am I doing something wrong and it's simply not working?
Here is my layer config:

const layerConfigurations = [
  {
      growEditionSizeTo: 100,
      layersOrder: [
      { name: "Background" },
      { name: "Body 3", options: { displayName: "Body", }, },
      { name: "Hair" },
      { name: "Hat" },
      { name: "Beard" },
      { name: "Glasses DR", options: { displayName: "Glasses", }, },
    ],
    layerItemsMaxRepeatedTraits: [
      { name: "Body 3/Areion 275", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 276", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 277", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 278", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 279", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 280", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 281", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 282", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 283", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 284", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 285", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 286", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 287", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 288", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 289", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 290", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 291", layerItemMaxRepeatedTrait: 1 },
      { name: "Body 3/Areion 292", layerItemMaxRepeatedTrait: 1 },
    ],
  },
];

![image](https://user-images.githubusercontent.com/99951837/166814786-e8ac81a0-1db1-4086-88e0-0bca48c0ff93.png)

Thank you for your time!

**Comment by thepeanutgalleryandco** [comment]
Hi @marcneagu .

Can you perhaps upload your full config.js file and perhaps zip your layers folder for me to test with? The tests that I have run before were with only a few items, but they should follow the same convention. I have also not used the options before to rename the layer, I am not sure if that might cause issues. Can you try to remove that please and run your test again?

**Comment by marcneagu** [comment]
Indeed the displayName option does play a role in messing up the filtration rule. I don't understand why though...I removed it and now it works as intended, but the json files will contain trait names that are wierd.
I guess a workaround for me now, would be to also manually rename the "Body x" trait, to "Body" in every single .json file 7600 times :D

But now a second problem emerges: "const uniqueDnaTorrance = xxxx;"
At some point, the program struggles so much in finding the last unused layers from a folder that it gives up. Maybe if I raise the DnaTorrance to 999999, by some kind of miracle the program will happen to chose the last unused layer(s) from the 7600 given.

I think a good feature would be for the layerItemsMaxRepeatedTraits function, to work in a global mode for the whole folder, without the need to also specify every single file from that folder.

**Comment by thepeanutgalleryandco** [comment]
@marcneagu thank you for testing, let's break your comment up into 3 parts.

**Part 1** - Can you test another case for me please? I want you to put the Body 3 to Body option back in, but then in your rules, please change it from Body 3 to Body as well, like in my example below.

const layerConfigurations = [
{
growEditionSizeTo: 100,
layersOrder: [
{ name: "Background" },
{ name: "Body 3", options: { displayName: "Body", }, },
{ name: "Hair" },
{ name: "Hat" },
{ name: "Beard" },
{ name: "Glasses DR", options: { displayName: "Glasses", }, },
],
layerItemsMaxRepeatedTraits: [
{ name: "Body/Areion 275", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 276", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 277", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 278", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 279", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 280", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 281", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 282", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 283", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 284", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 285", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 286", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 287", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 288", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 289", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 290", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 291", layerItemMaxRepeatedTrait: 1 },
{ name: "Body/Areion 292", layerItemMaxRepeatedTrait: 1 },
],
},
];


**Part 2** - Yes, uniqueDnaTorrance is used as fault tollerance as to how many failed generations due to filter rules or uniqueness the generation can take. There is no way getting around this as the code base tries all the different unique cases with every item. If you make that number extremely high, then it will eventually be able to fulfill all your generations. That is at least my understanding.


**Part 3** - So the feature that you would like to see is to specify a second configuration possibility on a layer level (along with "maxRepeatedTrait") so that it applies to each layer item inside the layer OR change how "maxRepeatedTrait" works to simply apply to each layer item in the layer? The second option probably makes more sense, but perhaps someone has a use-case for it, so building two options makes the most sense.

**Comment by marcneagu** [comment]
YES! It definitely works if I rename all from Body 3 to just Body! So big thank you for figuring that out!

As for part 3, I think maxRepeatedTrait has a separate use-case indeed, if i just want a specific layer item to repeat just x times.
The simplest thing I can think of for the function "layerItemsMaxRepeatedTrait" is:
layerItemsMaxRepeatedTraits: [
{ name: "Body/ListAllLayersFromFolder", layerItemMaxRepeatedTrait: 1 },
                              OR
{ name: "Body", layerItemMaxRepeatedTrait: 1 },
I am just starting my way to become a beginner developer, so I don't know how to implement this, but I would approach  it like this:
Main.js
 const listAllLayersFromFolder = layerConfigurations[layerConfigIndex].listAllLayersFromFolder;
Config.js
layerItemsMaxRepeatedTraits: [
{ name: "Body/listAllLayersFromFolder", layerItemMaxRepeatedTrait: 1 },

I am sorry if it makes no sense...

**Comment by thepeanutgalleryandco** [comment]
I will look at doing a new feature for this, but I think in terms of part 1 and 2, we can close this comment and carry on with part 3 on the feature if you are happy with that?

**Comment by marcneagu** [comment]
YES! It definitely works if I rename all from Body 3 to just Body! So big thank you for figuring that out!

As for part 3, I think maxRepeatedTrait has a separate use-case indeed, if i just want a specific layer item to repeat just x times.
The simplest thing I can think of for the function "layerItemsMaxRepeatedTrait" is:
layerItemsMaxRepeatedTraits: [
{ name: "Body/ListAllLayersFromFolder", layerItemMaxRepeatedTrait: 1 },
                              OR
{ name: "Body", layerItemMaxRepeatedTrait: 1 },
I am just starting my way to become a beginner developer, so I don't know how to implement this, but I would approach  it like this:
Main.js
 const listAllLayersFromFolder = layerConfigurations[layerConfigIndex].listAllLayersFromFolder;
Config.js
layerItemsMaxRepeatedTraits: [
{ name: "Body/listAllLayersFromFolder", layerItemMaxRepeatedTrait: 1 },

I am sorry if it makes no sense....

**Comment by marcneagu** [comment]
Yes, I am! My problem is solved, so thank you again! :)

**Comment by marcneagu** [comment]
Wow! Sound good! Thanks mate! I wont forget you! ;)

**Comment by thepeanutgalleryandco** [comment]
@marcneagu you can pull the latest version 1.7.7 and try to use the new "layerItemsMaxRepeatedTrait" setting.

**Comment by marcneagu** [comment]
I will do just that tonight, after I put my kids to sleep :)
I'll get back to you with a feedback!
